version: '3.8'
services:
  fitbaus:
    image: markraidc/fitbaus-public:latest
    container_name: fitbaus-app
    ports:
      - "9155:9000"
    volumes:
      - /volume1/appdata/fitbaus/profiles:/app/profiles
    environment:
      - PYTHONIOENCODING=utf-8
      - TZ=Etc/UTC
    restart: unless-stopped